import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-900 text-zinc-100`}>
        <header>
          <ul className="p-3 px-5 font-medium bg-zinc-800">
            <li className="rounded-md hover:text-blue-500 transition-colors hover:underline">
              <Link href={"/test/stripe-box"}>Stripe Box</Link>
            </li>
          </ul>
        </header>
        {children}
      </body>
    </html>
  );
}
